declare module 'lucide-react-native' {
  import { FC } from 'react';
  import { SvgProps } from 'react-native-svg';

  export interface LucideProps extends SvgProps {
    color?: string;
    size?: number | string;
    strokeWidth?: number | string;
  }

  export const ArrowLeft: FC<LucideProps>;
  export const ArrowUpDown: FC<LucideProps>;
  export const Bell: FC<LucideProps>;
  export const Calendar: FC<LucideProps>;
  export const Camera: FC<LucideProps>;
  export const Check: FC<LucideProps>;
  export const ChevronDown: FC<LucideProps>;
  export const ChevronLeft: FC<LucideProps>;
  export const ChevronRight: FC<LucideProps>;
  export const Chrome: FC<LucideProps>;
  export const Circle: FC<LucideProps>;
  export const CircleAlert: FC<LucideProps>;
  export const CircleCheck: FC<LucideProps>;
  export const Clock: FC<LucideProps>;
  export const Copy: FC<LucideProps>;
  export const CreditCard: FC<LucideProps>;
  export const CheckCircle: FC<LucideProps>;
  export const DollarSign: FC<LucideProps>;
  export const Download: FC<LucideProps>;
  export const ExternalLink: FC<LucideProps>;
  export const Eye: FC<LucideProps>;
  export const FileText: FC<LucideProps>;
  export const File: FC<LucideProps>;
  export const Filter: FC<LucideProps>;
  export const Globe: FC<LucideProps>;
  export const Grid3x3: FC<LucideProps>;
  export const Heart: FC<LucideProps>;
  export const Image: FC<LucideProps>;
  export const Info: FC<LucideProps>;
  export const Lock: FC<LucideProps>;
  export const LogIn: FC<LucideProps>;
  export const LogOut: FC<LucideProps>;
  export const Mail: FC<LucideProps>;
  export const MapPin: FC<LucideProps>;
  export const MessageCircle: FC<LucideProps>;
  export const Mic: FC<LucideProps>;
  export const MicOff: FC<LucideProps>;
  export const Minimize2: FC<LucideProps>;
  export const Minus: FC<LucideProps>;
  export const Moon: FC<LucideProps>;
  export const Package: FC<LucideProps>;
  export const Pause: FC<LucideProps>;
  export const Pencil: FC<LucideProps>;
  export const Percent: FC<LucideProps>;
  export const Phone: FC<LucideProps>;
  export const Play: FC<LucideProps>;
  export const Plus: FC<LucideProps>;
  export const Save: FC<LucideProps>;
  export const Search: FC<LucideProps>;
  export const Send: FC<LucideProps>;
  export const Settings: FC<LucideProps>;
  export const Share2: FC<LucideProps>;
  export const Shield: FC<LucideProps>;
  export const ShoppingBag: FC<LucideProps>;
  export const ShoppingCart: FC<LucideProps>;
  export const Smile: FC<LucideProps>;
  export const Star: FC<LucideProps>;
  export const Sun: FC<LucideProps>;
  export const Tag: FC<LucideProps>;
  export const ThumbsUp: FC<LucideProps>;
  export const Trash2: FC<LucideProps>;
  export const TrendingUp: FC<LucideProps>;
  export const TriangleAlert: FC<LucideProps>;
  export const Truck: FC<LucideProps>;
  export const Upload: FC<LucideProps>;
  export const User: FC<LucideProps>;
  export const UserCheck: FC<LucideProps>;
  export const UserPlus: FC<LucideProps>;
  export const UserX: FC<LucideProps>;
  export const Users: FC<LucideProps>;
  export const Video: FC<LucideProps>;
  export const X: FC<LucideProps>;
  export const XCircle: FC<LucideProps>;
  export const createLucideIcon: (name: string, iconNode: any[]) => FC<LucideProps>;
  export default {} as Record<string, FC<LucideProps>>;
}
