const fs = require('fs');
const path = require('path');

function log(...a){ console.log('[waku-shim]', ...a); }
function exists(p){ try { return fs.existsSync(p); } catch { return false; } }

function getCoreRoot() {
  try {
    return path.dirname(require.resolve('@waku/core/package.json'));
  } catch {
    const fallback = path.join(process.cwd(), 'node_modules', '@waku', 'core');
    return exists(fallback) ? fallback : null;
  }
}

function findVersionFile(coreRoot) {
  const candidates = [
    'lib/message/version_0.js',
    'lib/message/version-0.js',
    'dist/lib/message/version_0.js',
    'dist/lib/message/version-0.js',
    'lib/message/version_0/index.js',
    'dist/lib/message/version_0/index.js',
  ];
  for (const rel of candidates) {
    const abs = path.join(coreRoot, rel);
    if (exists(abs)) return { rel, abs };
  }
  return null;
}

function writeShim(coreRoot, actualRel) {
  const shimRel = 'lib/message/version_0.js';
  const shimAbs = path.join(coreRoot, shimRel);
  fs.mkdirSync(path.dirname(shimAbs), { recursive: true });

  const targetAbs = path.join(coreRoot, actualRel);
  const rel = path.relative(path.dirname(shimAbs), targetAbs).split(path.sep).join('/');
  const code = `// Auto-generated by waku-shim.js\nexport * from '${rel}';\nexport { default } from '${rel}';\n`;
  fs.writeFileSync(shimAbs, code, 'utf8');
  log('Created shim', shimRel, '->', actualRel);
}

(function main(){
  const coreRoot = getCoreRoot();
  if (!coreRoot) {
    console.error('[waku-shim] @waku/core not found. Did you install deps?');
    process.exit(1);
  }
  const actual = findVersionFile(coreRoot);
  if (!actual) {
    console.error('[waku-shim] Could not locate version_0 in @waku/core.');
    process.exit(1);
  }
  writeShim(coreRoot, actual.rel);
})();

