const fs = require('fs');
const path = require('path');

function log(...a){ console.log('[waku-shim]', ...a); }
function exists(p){ try { return fs.existsSync(p); } catch { return false; } }

function getCoreRoot() {
  try {
    return path.dirname(require.resolve('@waku/core/package.json'));
  } catch {
    const fallback = path.join(process.cwd(), 'node_modules', '@waku', 'core');
    return exists(fallback) ? fallback : null;
  }
}

function getUtilsRoot() {
  try {
    return path.dirname(require.resolve('@waku/utils/package.json'));
  } catch {
    const fallback = path.join(process.cwd(), 'node_modules', '@waku', 'utils');
    return exists(fallback) ? fallback : null;
  }
}

function findVersionFile(coreRoot, shimRel) {
  const candidates = [
    'lib/message/version-0.js',
    'dist/lib/message/version_0.js',
    'dist/lib/message/version-0.js',
    'lib/message/version_0/index.js',
    'dist/lib/message/version_0/index.js',
    'lib/message/version_0.js', // real file may exist here in future
  ];
  for (const rel of candidates) {
    if (rel === shimRel) continue; // skip self
    const abs = path.join(coreRoot, rel);
    if (exists(abs)) return { rel, abs };
  }
  return null;
}

function findBytesFile(utilsRoot, shimRel) {
  const candidates = [
    'dist/bytes/index.js',
    'lib/bytes/index.js',
    'dist/bytes.js',
    'lib/bytes.js',
    'bytes/index.js',
  ];
  for (const rel of candidates) {
    if (rel === shimRel) continue; // skip self
    const abs = path.join(utilsRoot, rel);
    if (exists(abs)) return { rel, abs };
  }
  return null;
}

function writeShim(pkgRoot, shimRel, actualRel) {
  if (actualRel === shimRel) {
    log('Shim already points to real file:', shimRel);
    return;
  }
  const shimAbs = path.join(pkgRoot, shimRel);
  fs.mkdirSync(path.dirname(shimAbs), { recursive: true });

  const targetAbs = path.join(pkgRoot, actualRel);
  const rel = path.relative(path.dirname(shimAbs), targetAbs).split(path.sep).join('/');
  const code = `// Auto-generated by waku-shim.js\nexport * from '${rel}';\nexport { default } from '${rel}';\n`;
  fs.writeFileSync(shimAbs, code, 'utf8');
  log('Created shim', shimRel, '->', actualRel);
}

(function main(){
  const coreRoot = getCoreRoot();
  if (!coreRoot) {
    console.error('[waku-shim] @waku/core not found. Did you install deps?');
    process.exit(1);
  }
  const shimVersion = 'lib/message/version_0.js';
  const actual = findVersionFile(coreRoot, shimVersion);
  if (!actual) {
    console.error('[waku-shim] Could not locate version_0 in @waku/core.');
    process.exit(1);
  }
  writeShim(coreRoot, shimVersion, actual.rel);

  const utilsRoot = getUtilsRoot();
  if (!utilsRoot) {
    console.error('[waku-shim] @waku/utils not found. Did you install deps?');
    process.exit(1);
  }
  const shimBytes = path.join('bytes', 'index.js');
  const bytes = findBytesFile(utilsRoot, shimBytes);
  if (!bytes) {
    console.error('[waku-shim] Could not locate bytes module in @waku/utils.');
    process.exit(1);
  }
  writeShim(utilsRoot, shimBytes, bytes.rel);
})();

